### ISSUE TITLE
K8s Cluster Open Access

### ISSUE THREAD

**Issue by erismaster** [nicholasjackson/fake-service#5]
Hi,

I wanted to report that a kubernetes cluster that may possibly be under your control is open and allows dashboard access without auth.

http://165.22.195.243:8443/

I would recommend closing this up before someone starts mining cryptocurrency 😄

**Comment by nicholasjackson** [comment]
Ah thanks,

That is my remote dev environment which I use from my chromebook. I completely forgot I had that running and have shut it down.

Thanks so much for the heads up.

Nic
