### ISSUE TITLE
Outdataed Datadog Trace Library

### ISSUE THREAD

**Issue by mlindes** [nicholasjackson/fake-service#82]
Hi!
Could you release a new version of this to use the updated dd-trace library?
[`go.mod` currently shows dd-trace-go.v1 at v1.18.0](https://github.com/nicholasjackson/fake-service/blob/main/go.mod#L24)
but Datadog's Unified Service Tagging [requires v1.24.0](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=ecs#requirements) or higher

**Comment by nicholasjackson** [comment]
Apologies, I have updated this to `gopkg.in/DataDog/dd-trace-go.v1 v1.48.0` 

Kind regards,

Nic
